FT.manifest({
    "filename": "index.html",
    "width": 300,
    "height": 250,
    "clickTagCount": 1,
    "hideBrowsers": ["ie11"],
    "instantAds": [
        { "name": "mag", "type": "text", "default": "hyper_u" },
        { "name": "nom_mag", "type": "text", "default": "Grand Quevilly Grand Quevilly Grand Quevilly Grand Quevilly" },
        { "name": "title", "type": "text", "default": "Découvrez nos promos du moment Découvrez nos promos du moment" },
        { "name": "homepage", "type": "image", "default": "Asset/homepage.jpg" },
        { "name": "date_op_generique", "type": "text", "default": "Du 08/11 au 19/11/2022" },
        { "name": "adresse", "type": "text", "default": "Rue du Bois Cany<br>Centre commercial<br>76120 Le Grand Quevally" },
        { "name": "cta", "type": "text", "default": "Je consulte" },
        { "name": "bg_img_product0", "type": "image", "default": "asset/empty.png" },

        { "name": "date_product1", "type": "text", "default": "Du 08/11 au 19/11/2023" },
        { "name": "orientation_product1", "type": "text", "default": "portrait" },
        { "name": "bg_img_product1", "type": "image", "default": "asset/empty.png" },
        { "name": "color_product1", "type": "text", "default": "coral" },
        { "name": "txt_product1", "type": "text", "default": "Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Trio-Caps super croix" },
        { "name": "product1_img", "type": "image", "default": "asset/c.jpg" },
        { "name": "capsule_prix_product1", "type": "image", "default": "asset/testCapsule.png" },
        { "name": "legal_product1", "type": "text", "default": "Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix Lessive Trio-Caps super croix" },
        { "name": "pictos_product1", "type": "image", "default": "asset/picto3.png" },
        { "name": "pictos_product1_bg", "type": "text", "default": "true" },
        { "name": "legal_pictos_product1", "type": "image", "default": "asset/picto3.png" },
        { "name": "game_product1", "type": "image", "default": "asset/empty.png" },

        { "name": "date_product2", "type": "text", "default": "Du 08/11 au 19/11/2024" },
        { "name": "orientation_product2", "type": "text", "default": "vertical" },
        { "name": "txt_product2", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "bg_img_product2", "type": "image", "default": "asset/empty.png" },
        { "name": "color_product2", "type": "text", "default": "mint" },
        { "name": "product2_img", "type": "image", "default": "asset/test2.png" },
        { "name": "capsule_prix_product2", "type": "image", "default": "asset/testCapsule.png" },
        { "name": "legal_product2", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "pictos_product2", "type": "image", "default": "asset/picto3.png" },
        { "name": "pictos_product2_bg", "type": "text", "default": "false" },
        { "name": "legal_pictos_product2", "type": "image", "default": "asset/picto3.png" },
        { "name": "game_product2", "type": "image", "default": "asset/empty.png" },

        { "name": "date_product3", "type": "text", "default": "Du 08/11 au 19/11/2025" },
        { "name": "orientation_product3", "type": "text", "default": "vertical" },
        { "name": "txt_product3", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "bg_img_product3", "type": "image", "default": "asset/empty.png" },
        { "name": "color_product3", "type": "text", "default": "mint" },
        { "name": "product3_img", "type": "image", "default": "asset/test2.png" },
        { "name": "capsule_prix_product3", "type": "image", "default": "asset/testCapsule.png" },
        { "name": "legal_product3", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "pictos_product3", "type": "image", "default": "asset/picto3.png" },
        { "name": "pictos_product3_bg", "type": "text", "default": "false" },
        { "name": "legal_pictos_product3", "type": "image", "default": "asset/picto3.png" },
        { "name": "game_product3", "type": "image", "default": "asset/empty.png" },

        { "name": "date_product4", "type": "text", "default": "Du 08/11 au 19/11/2026" },
        { "name": "orientation_product4", "type": "text", "default": "vertical" },
        { "name": "txt_product4", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "bg_img_product4", "type": "image", "default": "asset/empty.png" },
        { "name": "color_product4", "type": "text", "default": "mint" },
        { "name": "product4_img", "type": "image", "default": "asset/test2.png" },
        { "name": "capsule_prix_product4", "type": "image", "default": "asset/testCapsule.png" },
        { "name": "legal_product4", "type": "text", "default": "Lessive Trio-Caps super croix" },
        { "name": "pictos_product4", "type": "image", "default": "asset/picto3.png" },
        { "name": "pictos_product4_bg", "type": "text", "default": "false" },
        { "name": "legal_pictos_product4", "type": "image", "default": "asset/picto3.png" },
        { "name": "game_product4", "type": "image", "default": "asset/empty.png" },

        { "name": "clickTag", "type": "text", "default": "https://promos.magasins-u.com/" }
    ]
});