<?php
// ICI, IL FAUT AUSSI DÉMARRER LA SESSION

// ICI CHARGER LA DATABASE

// ICI CHARGER LE MODEL "users.model.php"

// ON A BESOIN D'INITIALISER CES VARIABLES POUR NE PAS FAIRE PLANTER LE PHTML
$email      = ''; // INITIALISATION DE LA VARIABLE $email (PAS TOUCHE)
$password   = ''; // INITIALISATION DE LA VARIABLE $password (PAS TOUCHE)
$message    = ''; // INITIALISATION DU MESSAGE UTILISATEUR (PAS TOUCHE)

// SI $_POST['email'] ET $_POST['password'] SONT DÉFINIS ALORS

    // RÉCUPÉRER $_POST['email'] DANS UNE VARIABLE

    // RÉCUPÉRER $_POST['password'] DANS UNE VARIABLE

    // DEMANDER AU MODEL "users" DE CONNECTER L'UTILISATEUR AVEC CET EMAIL ET CE MOT DE PASSE

    // SI LA RÉPONSE EST NULLE ALORS

        // ECRIRE UN MESSAGE DE MAUVAISE CONNECTION À L'UTILISATEUR
        
    // SINON (L'UTILISATEUR EST CONNECTÉ)

        // REDIRECTION VERS LA PAGE DE PROFIL
        
        // TUER LE PROCESS (POUR NE PAS ENVOYER LE PHTML DE LA PAGE DE CONNEXION)

    // FIN SI

// FIN SI

// CHARGEMENT DU TEMPLATE (PAS TOUCHE)
require_once './templates/index.phtml';
