<?php
// ICI, IL FAUT AUSSI DÉMARRER LA SESSION (ET OUI, SUR TOUTES LES PAGES)

// ICI CHARGER LA DATABASE

// ICI CHARGER LE MODEL "users.model.php"

// CHARGEMENT DU FICHIER DE DEBUG POUR TESTS

// VARIABLES UTILISÉES PAR LE TEMPLATE (PAS TOUCHE)
$agent          = [];   // (PAS TOUCHE)
$firstname      = '';   // (PAS TOUCHE)
$lastname       = '';   // (PAS TOUCHE)
$email          = '';   // (PAS TOUCHE)
$description    = '';   // (PAS TOUCHE)
$actorFirstname = '';   // (PAS TOUCHE)
$actorLastname  = '';   // (PAS TOUCHE)
$actorBirthDate = '';   // (PAS TOUCHE)
$actorPhoto     = '';   // (PAAAAS TOOOUUUUUCHE !!!!)

// SI IL N'Y A PAS DE UID EN SESSION, RETOURNER À LA PAGE DE CONNEXION

    // REDIRECTION VERS LA PAGE D'ACCUEIL

// FIN SI

// RÉCUPÉRER L'UID EN SESSION

// ICI, DEMANDER AU MODEL 'USERS' DE NOUS DONNER TOUTES LES INFOS DE L'AGENT AVEC CET UID (LES CHARGER DANS $agent)

// SI $agent N'EST PAS VIDE

    // CHARGER TOUTES LES VARIABLES (CI-DESSUS) AVEC LES BONNES DONNÉES AVANT DE LES ENVOYER AU TEMPLATE

    // POUR LA DATE : CRÉER UNE DATE AVEC LA DATE ENREGISTRÉE EN BDD

    // METTRE DANS $actorBirthDate LA FORMATÉE AU FORMAT JJ/MM/AAAA (NOTE : ÇA N'EXISTE PAS, ÇA, C'EST DU FRANÇAIS, CHERCHEZ DANS LA DOC)

// FIN SI

// CHARGEMENT DU TEMPLATE (PAS TOUCHE)
require_once 'templates/profil.phtml';